// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.x.protobuffer;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SendMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 command = 1;
    /**
     * <code>required int32 command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>required int32 command = 1;</code>
     */
    int getCommand();

    // required bytes msgType = 2;
    /**
     * <code>required bytes msgType = 2;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required bytes msgType = 2;</code>
     */
    com.google.protobuf.ByteString getMsgType();

    // repeated string strValue = 3;
    /**
     * <code>repeated string strValue = 3;</code>
     */
    java.util.List<java.lang.String>
    getStrValueList();
    /**
     * <code>repeated string strValue = 3;</code>
     */
    int getStrValueCount();
    /**
     * <code>repeated string strValue = 3;</code>
     */
    java.lang.String getStrValue(int index);
    /**
     * <code>repeated string strValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrValueBytes(int index);

    // repeated int32 intValue = 4;
    /**
     * <code>repeated int32 intValue = 4;</code>
     */
    java.util.List<java.lang.Integer> getIntValueList();
    /**
     * <code>repeated int32 intValue = 4;</code>
     */
    int getIntValueCount();
    /**
     * <code>repeated int32 intValue = 4;</code>
     */
    int getIntValue(int index);

    // repeated bool boolValue = 5;
    /**
     * <code>repeated bool boolValue = 5;</code>
     */
    java.util.List<java.lang.Boolean> getBoolValueList();
    /**
     * <code>repeated bool boolValue = 5;</code>
     */
    int getBoolValueCount();
    /**
     * <code>repeated bool boolValue = 5;</code>
     */
    boolean getBoolValue(int index);

    // repeated bytes byteValue = 6;
    /**
     * <code>repeated bytes byteValue = 6;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getByteValueList();
    /**
     * <code>repeated bytes byteValue = 6;</code>
     */
    int getByteValueCount();
    /**
     * <code>repeated bytes byteValue = 6;</code>
     */
    com.google.protobuf.ByteString getByteValue(int index);

    // repeated int64 longValue = 7;
    /**
     * <code>repeated int64 longValue = 7;</code>
     */
    java.util.List<java.lang.Long> getLongValueList();
    /**
     * <code>repeated int64 longValue = 7;</code>
     */
    int getLongValueCount();
    /**
     * <code>repeated int64 longValue = 7;</code>
     */
    long getLongValue(int index);
  }
  /**
   * Protobuf type {@code protobuffer.SendMessage}
   */
  public static final class SendMessage extends
      com.google.protobuf.GeneratedMessage
      implements SendMessageOrBuilder {
    // Use SendMessage.newBuilder() to construct.
    private SendMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SendMessage defaultInstance;
    public static SendMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SendMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SendMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              command_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgType_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                strValue_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              strValue_.add(input.readBytes());
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                intValue_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              intValue_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                intValue_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                intValue_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                boolValue_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000010;
              }
              boolValue_.add(input.readBool());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                boolValue_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                boolValue_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                byteValue_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000020;
              }
              byteValue_.add(input.readBytes());
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                longValue_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              longValue_.add(input.readInt64());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                longValue_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                longValue_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          strValue_ = new com.google.protobuf.UnmodifiableLazyStringList(strValue_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          intValue_ = java.util.Collections.unmodifiableList(intValue_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          boolValue_ = java.util.Collections.unmodifiableList(boolValue_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          byteValue_ = java.util.Collections.unmodifiableList(byteValue_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          longValue_ = java.util.Collections.unmodifiableList(longValue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.x.protobuffer.Message.internal_static_protobuffer_SendMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.x.protobuffer.Message.internal_static_protobuffer_SendMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.x.protobuffer.Message.SendMessage.class, com.x.protobuffer.Message.SendMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SendMessage> PARSER =
        new com.google.protobuf.AbstractParser<SendMessage>() {
      public SendMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>required int32 command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 command = 1;</code>
     */
    public int getCommand() {
      return command_;
    }

    // required bytes msgType = 2;
    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msgType_;
    /**
     * <code>required bytes msgType = 2;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes msgType = 2;</code>
     */
    public com.google.protobuf.ByteString getMsgType() {
      return msgType_;
    }

    // repeated string strValue = 3;
    public static final int STRVALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList strValue_;
    /**
     * <code>repeated string strValue = 3;</code>
     */
    public java.util.List<java.lang.String>
        getStrValueList() {
      return strValue_;
    }
    /**
     * <code>repeated string strValue = 3;</code>
     */
    public int getStrValueCount() {
      return strValue_.size();
    }
    /**
     * <code>repeated string strValue = 3;</code>
     */
    public java.lang.String getStrValue(int index) {
      return strValue_.get(index);
    }
    /**
     * <code>repeated string strValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrValueBytes(int index) {
      return strValue_.getByteString(index);
    }

    // repeated int32 intValue = 4;
    public static final int INTVALUE_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> intValue_;
    /**
     * <code>repeated int32 intValue = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getIntValueList() {
      return intValue_;
    }
    /**
     * <code>repeated int32 intValue = 4;</code>
     */
    public int getIntValueCount() {
      return intValue_.size();
    }
    /**
     * <code>repeated int32 intValue = 4;</code>
     */
    public int getIntValue(int index) {
      return intValue_.get(index);
    }

    // repeated bool boolValue = 5;
    public static final int BOOLVALUE_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Boolean> boolValue_;
    /**
     * <code>repeated bool boolValue = 5;</code>
     */
    public java.util.List<java.lang.Boolean>
        getBoolValueList() {
      return boolValue_;
    }
    /**
     * <code>repeated bool boolValue = 5;</code>
     */
    public int getBoolValueCount() {
      return boolValue_.size();
    }
    /**
     * <code>repeated bool boolValue = 5;</code>
     */
    public boolean getBoolValue(int index) {
      return boolValue_.get(index);
    }

    // repeated bytes byteValue = 6;
    public static final int BYTEVALUE_FIELD_NUMBER = 6;
    private java.util.List<com.google.protobuf.ByteString> byteValue_;
    /**
     * <code>repeated bytes byteValue = 6;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getByteValueList() {
      return byteValue_;
    }
    /**
     * <code>repeated bytes byteValue = 6;</code>
     */
    public int getByteValueCount() {
      return byteValue_.size();
    }
    /**
     * <code>repeated bytes byteValue = 6;</code>
     */
    public com.google.protobuf.ByteString getByteValue(int index) {
      return byteValue_.get(index);
    }

    // repeated int64 longValue = 7;
    public static final int LONGVALUE_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Long> longValue_;
    /**
     * <code>repeated int64 longValue = 7;</code>
     */
    public java.util.List<java.lang.Long>
        getLongValueList() {
      return longValue_;
    }
    /**
     * <code>repeated int64 longValue = 7;</code>
     */
    public int getLongValueCount() {
      return longValue_.size();
    }
    /**
     * <code>repeated int64 longValue = 7;</code>
     */
    public long getLongValue(int index) {
      return longValue_.get(index);
    }

    private void initFields() {
      command_ = 0;
      msgType_ = com.google.protobuf.ByteString.EMPTY;
      strValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      intValue_ = java.util.Collections.emptyList();
      boolValue_ = java.util.Collections.emptyList();
      byteValue_ = java.util.Collections.emptyList();
      longValue_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, command_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, msgType_);
      }
      for (int i = 0; i < strValue_.size(); i++) {
        output.writeBytes(3, strValue_.getByteString(i));
      }
      for (int i = 0; i < intValue_.size(); i++) {
        output.writeInt32(4, intValue_.get(i));
      }
      for (int i = 0; i < boolValue_.size(); i++) {
        output.writeBool(5, boolValue_.get(i));
      }
      for (int i = 0; i < byteValue_.size(); i++) {
        output.writeBytes(6, byteValue_.get(i));
      }
      for (int i = 0; i < longValue_.size(); i++) {
        output.writeInt64(7, longValue_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, command_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msgType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < strValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(strValue_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStrValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < intValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(intValue_.get(i));
        }
        size += dataSize;
        size += 1 * getIntValueList().size();
      }
      {
        int dataSize = 0;
        dataSize = 1 * getBoolValueList().size();
        size += dataSize;
        size += 1 * getBoolValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < byteValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(byteValue_.get(i));
        }
        size += dataSize;
        size += 1 * getByteValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < longValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(longValue_.get(i));
        }
        size += dataSize;
        size += 1 * getLongValueList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.x.protobuffer.Message.SendMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x.protobuffer.Message.SendMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x.protobuffer.Message.SendMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.x.protobuffer.Message.SendMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.x.protobuffer.Message.SendMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.x.protobuffer.Message.SendMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.x.protobuffer.Message.SendMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.x.protobuffer.Message.SendMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.x.protobuffer.Message.SendMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.x.protobuffer.Message.SendMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.x.protobuffer.Message.SendMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuffer.SendMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.x.protobuffer.Message.SendMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.x.protobuffer.Message.internal_static_protobuffer_SendMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.x.protobuffer.Message.internal_static_protobuffer_SendMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.x.protobuffer.Message.SendMessage.class, com.x.protobuffer.Message.SendMessage.Builder.class);
      }

      // Construct using com.x.protobuffer.Message.SendMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        strValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        intValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        boolValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        byteValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        longValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.x.protobuffer.Message.internal_static_protobuffer_SendMessage_descriptor;
      }

      public com.x.protobuffer.Message.SendMessage getDefaultInstanceForType() {
        return com.x.protobuffer.Message.SendMessage.getDefaultInstance();
      }

      public com.x.protobuffer.Message.SendMessage build() {
        com.x.protobuffer.Message.SendMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.x.protobuffer.Message.SendMessage buildPartial() {
        com.x.protobuffer.Message.SendMessage result = new com.x.protobuffer.Message.SendMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgType_ = msgType_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          strValue_ = new com.google.protobuf.UnmodifiableLazyStringList(
              strValue_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.strValue_ = strValue_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          intValue_ = java.util.Collections.unmodifiableList(intValue_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.intValue_ = intValue_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          boolValue_ = java.util.Collections.unmodifiableList(boolValue_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.boolValue_ = boolValue_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          byteValue_ = java.util.Collections.unmodifiableList(byteValue_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.byteValue_ = byteValue_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          longValue_ = java.util.Collections.unmodifiableList(longValue_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.longValue_ = longValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.x.protobuffer.Message.SendMessage) {
          return mergeFrom((com.x.protobuffer.Message.SendMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.x.protobuffer.Message.SendMessage other) {
        if (other == com.x.protobuffer.Message.SendMessage.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (!other.strValue_.isEmpty()) {
          if (strValue_.isEmpty()) {
            strValue_ = other.strValue_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStrValueIsMutable();
            strValue_.addAll(other.strValue_);
          }
          onChanged();
        }
        if (!other.intValue_.isEmpty()) {
          if (intValue_.isEmpty()) {
            intValue_ = other.intValue_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIntValueIsMutable();
            intValue_.addAll(other.intValue_);
          }
          onChanged();
        }
        if (!other.boolValue_.isEmpty()) {
          if (boolValue_.isEmpty()) {
            boolValue_ = other.boolValue_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureBoolValueIsMutable();
            boolValue_.addAll(other.boolValue_);
          }
          onChanged();
        }
        if (!other.byteValue_.isEmpty()) {
          if (byteValue_.isEmpty()) {
            byteValue_ = other.byteValue_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureByteValueIsMutable();
            byteValue_.addAll(other.byteValue_);
          }
          onChanged();
        }
        if (!other.longValue_.isEmpty()) {
          if (longValue_.isEmpty()) {
            longValue_ = other.longValue_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureLongValueIsMutable();
            longValue_.addAll(other.longValue_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasMsgType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.x.protobuffer.Message.SendMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.x.protobuffer.Message.SendMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 command = 1;
      private int command_ ;
      /**
       * <code>required int32 command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 command = 1;</code>
       */
      public int getCommand() {
        return command_;
      }
      /**
       * <code>required int32 command = 1;</code>
       */
      public Builder setCommand(int value) {
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = 0;
        onChanged();
        return this;
      }

      // required bytes msgType = 2;
      private com.google.protobuf.ByteString msgType_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msgType = 2;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes msgType = 2;</code>
       */
      public com.google.protobuf.ByteString getMsgType() {
        return msgType_;
      }
      /**
       * <code>required bytes msgType = 2;</code>
       */
      public Builder setMsgType(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msgType = 2;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }

      // repeated string strValue = 3;
      private com.google.protobuf.LazyStringList strValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStrValueIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          strValue_ = new com.google.protobuf.LazyStringArrayList(strValue_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public java.util.List<java.lang.String>
          getStrValueList() {
        return java.util.Collections.unmodifiableList(strValue_);
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public int getStrValueCount() {
        return strValue_.size();
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public java.lang.String getStrValue(int index) {
        return strValue_.get(index);
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrValueBytes(int index) {
        return strValue_.getByteString(index);
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public Builder setStrValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrValueIsMutable();
        strValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public Builder addStrValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrValueIsMutable();
        strValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public Builder addAllStrValue(
          java.lang.Iterable<java.lang.String> values) {
        ensureStrValueIsMutable();
        super.addAll(values, strValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public Builder clearStrValue() {
        strValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string strValue = 3;</code>
       */
      public Builder addStrValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrValueIsMutable();
        strValue_.add(value);
        onChanged();
        return this;
      }

      // repeated int32 intValue = 4;
      private java.util.List<java.lang.Integer> intValue_ = java.util.Collections.emptyList();
      private void ensureIntValueIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          intValue_ = new java.util.ArrayList<java.lang.Integer>(intValue_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 intValue = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getIntValueList() {
        return java.util.Collections.unmodifiableList(intValue_);
      }
      /**
       * <code>repeated int32 intValue = 4;</code>
       */
      public int getIntValueCount() {
        return intValue_.size();
      }
      /**
       * <code>repeated int32 intValue = 4;</code>
       */
      public int getIntValue(int index) {
        return intValue_.get(index);
      }
      /**
       * <code>repeated int32 intValue = 4;</code>
       */
      public Builder setIntValue(
          int index, int value) {
        ensureIntValueIsMutable();
        intValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 intValue = 4;</code>
       */
      public Builder addIntValue(int value) {
        ensureIntValueIsMutable();
        intValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 intValue = 4;</code>
       */
      public Builder addAllIntValue(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIntValueIsMutable();
        super.addAll(values, intValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 intValue = 4;</code>
       */
      public Builder clearIntValue() {
        intValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated bool boolValue = 5;
      private java.util.List<java.lang.Boolean> boolValue_ = java.util.Collections.emptyList();
      private void ensureBoolValueIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          boolValue_ = new java.util.ArrayList<java.lang.Boolean>(boolValue_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bool boolValue = 5;</code>
       */
      public java.util.List<java.lang.Boolean>
          getBoolValueList() {
        return java.util.Collections.unmodifiableList(boolValue_);
      }
      /**
       * <code>repeated bool boolValue = 5;</code>
       */
      public int getBoolValueCount() {
        return boolValue_.size();
      }
      /**
       * <code>repeated bool boolValue = 5;</code>
       */
      public boolean getBoolValue(int index) {
        return boolValue_.get(index);
      }
      /**
       * <code>repeated bool boolValue = 5;</code>
       */
      public Builder setBoolValue(
          int index, boolean value) {
        ensureBoolValueIsMutable();
        boolValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool boolValue = 5;</code>
       */
      public Builder addBoolValue(boolean value) {
        ensureBoolValueIsMutable();
        boolValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool boolValue = 5;</code>
       */
      public Builder addAllBoolValue(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureBoolValueIsMutable();
        super.addAll(values, boolValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool boolValue = 5;</code>
       */
      public Builder clearBoolValue() {
        boolValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // repeated bytes byteValue = 6;
      private java.util.List<com.google.protobuf.ByteString> byteValue_ = java.util.Collections.emptyList();
      private void ensureByteValueIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          byteValue_ = new java.util.ArrayList<com.google.protobuf.ByteString>(byteValue_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated bytes byteValue = 6;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getByteValueList() {
        return java.util.Collections.unmodifiableList(byteValue_);
      }
      /**
       * <code>repeated bytes byteValue = 6;</code>
       */
      public int getByteValueCount() {
        return byteValue_.size();
      }
      /**
       * <code>repeated bytes byteValue = 6;</code>
       */
      public com.google.protobuf.ByteString getByteValue(int index) {
        return byteValue_.get(index);
      }
      /**
       * <code>repeated bytes byteValue = 6;</code>
       */
      public Builder setByteValue(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteValueIsMutable();
        byteValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteValue = 6;</code>
       */
      public Builder addByteValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteValueIsMutable();
        byteValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteValue = 6;</code>
       */
      public Builder addAllByteValue(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureByteValueIsMutable();
        super.addAll(values, byteValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteValue = 6;</code>
       */
      public Builder clearByteValue() {
        byteValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      // repeated int64 longValue = 7;
      private java.util.List<java.lang.Long> longValue_ = java.util.Collections.emptyList();
      private void ensureLongValueIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          longValue_ = new java.util.ArrayList<java.lang.Long>(longValue_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated int64 longValue = 7;</code>
       */
      public java.util.List<java.lang.Long>
          getLongValueList() {
        return java.util.Collections.unmodifiableList(longValue_);
      }
      /**
       * <code>repeated int64 longValue = 7;</code>
       */
      public int getLongValueCount() {
        return longValue_.size();
      }
      /**
       * <code>repeated int64 longValue = 7;</code>
       */
      public long getLongValue(int index) {
        return longValue_.get(index);
      }
      /**
       * <code>repeated int64 longValue = 7;</code>
       */
      public Builder setLongValue(
          int index, long value) {
        ensureLongValueIsMutable();
        longValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 longValue = 7;</code>
       */
      public Builder addLongValue(long value) {
        ensureLongValueIsMutable();
        longValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 longValue = 7;</code>
       */
      public Builder addAllLongValue(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureLongValueIsMutable();
        super.addAll(values, longValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 longValue = 7;</code>
       */
      public Builder clearLongValue() {
        longValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuffer.SendMessage)
    }

    static {
      defaultInstance = new SendMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuffer.SendMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuffer_SendMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuffer_SendMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\013protobuffer\"\214\001\n\013SendMes" +
      "sage\022\017\n\007command\030\001 \002(\005\022\017\n\007msgType\030\002 \002(\014\022\020" +
      "\n\010strValue\030\003 \003(\t\022\020\n\010intValue\030\004 \003(\005\022\021\n\tbo" +
      "olValue\030\005 \003(\010\022\021\n\tbyteValue\030\006 \003(\014\022\021\n\tlong" +
      "Value\030\007 \003(\003B\034\n\021com.x.protobufferB\007Messag" +
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuffer_SendMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuffer_SendMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuffer_SendMessage_descriptor,
              new java.lang.String[] { "Command", "MsgType", "StrValue", "IntValue", "BoolValue", "ByteValue", "LongValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
